language: rust

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda env create -f environment.yaml

before_script:
  - rustup install nightly
  - rustup override set nightly
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - conda activate pyrpds
  - black . --check
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - maturin develop --release
  - pytest