[project]
name = "pyrpds"

homepage = "https://github.com/arakhmat/pyrpds"
repository = "https://github.com/arakhmat/pyrpds"
documentation = "https://github.com/arakhmat/pyrpds"

[tool.black]
target-version = ['py37', 'py38']
include = '(\.pyi?)$'